// This file is auto-generated by scripts/generateChangelog.js. Do not edit directly.
window.ALOHA_CHANGELOG = [
  {
    "hash": "7f72f4a",
    "date": "2025-01-13",
    "author": "Muhammad Faiz",
    "subject": "feat(v1.1.5): enhance version control system",
    "body": "- Implement robust version checking with timestamp preservation\n- Add periodic version checks in script.js\n- Update service worker cache management\n- Enhance sync-version.js to maintain timestamp\n- Improve version.json structure\n\nTechnical improvements:\n- Version-specific cache naming in service worker\n- Automatic cache invalidation on version changes\n- Preserved user preferences during updates\n- Enhanced version sync between config.js and version.json\n- Added timestamp persistence in version tracking"
  },
  {
    "hash": "1976892",
    "date": "2025-01-13",
    "author": "Muhammad Faiz",
    "subject": "fix: enhance modal interaction and drag functionality",
    "body": "- Improve touch event handling for modal headers\n- Fix close button functionality on mobile devices\n- Optimize drag operations to maintain other interactive elements\n- Update version tracking\n- Refine configuration settings"
  },
  {
    "hash": "aec3ef1",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "Update PWA screenshots to match manifest specifications",
    "body": "- Desktop screenshot: 1280x800px\n- Mobile screenshot: 390x844px\n- Maintained aspect ratio with white borders\n- Optimized for PWA store listings\n- Enhanced visual presentation across devices\n\nThese screenshots are crucial for:\n1. PWA installation prompts\n2. App store listings\n3. Web manifest compliance\n4. Cross-device compatibility"
  },
  {
    "hash": "cdca9ee",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "Implement centralized version management system",
    "body": "- Add config.js as single source of truth for version\n- Add automated version sync between config.js and version.json\n- Enhance service worker for version checking\n- Update .gitignore for better project management\n\nTo get the latest version:\n\nDesktop (Windows/Mac):\n1. Chrome/Edge: Press Ctrl+Shift+R (Windows) or Cmd+Shift+R (Mac)\n2. Firefox: Press Ctrl+F5 (Windows) or Cmd+Shift+R (Mac)\n3. Safari: Press Option+Cmd+R\n\nMobile:\n1. Android Chrome:\n   - Open menu (3 dots)\n   - Hold refresh button\n   - Select 'Empty Cache and Hard Reload'\n\n2. iOS Safari:\n   - Settings > Safari\n   - Clear History and Website Data\n   - Return to app and refresh\n\nOr visit Settings in your browser and clear cache for this site specifically."
  },
  {
    "hash": "6501502",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "Update viewport scaling and refresh screenshots",
    "body": ""
  },
  {
    "hash": "daedd6b",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "UI: Increase modal height and bump version to 1.1.1",
    "body": "- Increased max-height from 30vh to 40vh in arithmetic and game modals for better content visibility\n- Updated app version to 1.1.1"
  },
  {
    "hash": "4f18987",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "feat: centralize version management in script.js",
    "body": "- Move APP_VERSION constant to script.js for centralized version control\n- Remove version messaging from service worker for cleaner separation\n- Add version display initialization in core startup\n- Simplify service worker to focus on caching functionality\n- Improve startup sequence with version display"
  },
  {
    "hash": "3f73ff7",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "fix: CSS transform property placement and responsive styling improvements",
    "body": "- Fixed transform property placement in styles.css media query\n- Enhanced responsive design for mobile devices\n- Updated service worker cache handling\n- Improved tutorial styling and interactions"
  },
  {
    "hash": "4430093",
    "date": "2025-01-12",
    "author": "Muhammad Faiz",
    "subject": "fix: Correctly implement \"Guide Me\" functionality and update styles",
    "body": "This commit addresses the issue where the \"Guide Me\" button in the game was not functioning due to a ReferenceError. The error was caused by attempting to use an undefined variable .\n\nThe fix involves:\n- Correctly selecting the  element to append the tutorial content.\n- Ensuring the tutorial content is placed within the correct scope.\n- Removing the usage of the undefined  variable.\n\nAdditionally, this commit includes updates to:\n- : No functional changes, but included in the commit as it was modified in the previous step.\n- : No functional changes, but included in the commit as it was modified in the previous step.\n- : Corrected the \"Guide Me\" functionality and included minor refactoring.\n- : No functional changes, but included in the commit as it was modified in the previous step.\n\nThese changes ensure the \"Guide Me\" button works as expected and the code is more robust."
  },
  {
    "hash": "8af95c8",
    "date": "2025-01-11",
    "author": "Muhammad Faiz",
    "subject": "Enhance initialization sequence and dependency management",
    "body": "- Expose ArithmeticGame class globally in game.js\n- Optimize script loading order in index.html\n- Improve dependency checks in script.js with timeout protection"
  },
  {
    "hash": "1dd9e52",
    "date": "2025-01-11",
    "author": "Muhammad Faiz",
    "subject": "Enhance ServiceWorker with detailed logging and error handling",
    "body": "- Add comprehensive logging for caching operations\n- Implement detailed error tracking for failed asset caching\n- Add request URL logging for better debugging\n- Organize assets into clear categories\n- Improve request filtering for better performance\n- Add comments for maintainability"
  },
  {
    "hash": "39f2868",
    "date": "2025-01-11",
    "author": "Muhammad Faiz",
    "subject": "Fix bead placement, improve modal handling, and enhance addition steps",
    "body": "This commit addresses several key issues and enhancements:\n\n- Resolved the bead placement issue where activated beads were not properly positioned on the shaft after implementing dynamic abacus sizing. This ensures accurate visual representation of bead values.\n\n- Modified the game and practice windows to open as movable/draggable popup windows instead of being displayed at the bottom of the page. This provides a more flexible and user-friendly interface.\n\n- Updated the addition steps to ensure they start from the smallest digit (ones place) first. This aligns with the abacus calculation method and provides a more logical learning experience.\n\n- Implemented the 5's complement method for addition, providing a more comprehensive guide for bead movements.\n\n- Added missing translations for bead movement instructions in translation.csv.\n\n- Improved modal handling and visibility management during language changes.\n\n- Refactored code for better organization and readability.\n\nThese changes significantly improve the user experience and provide a more robust and accurate abacus learning tool."
  },
  {
    "hash": "13e86c3",
    "date": "2025-01-11",
    "author": "Muhammad Faiz",
    "subject": "feat: implement responsive typography and fluid scaling for abacus UI",
    "body": ""
  },
  {
    "hash": "f13bbf1",
    "date": "2025-01-11",
    "author": "Muhammad Faiz",
    "subject": "fix: Update service worker registration path",
    "body": ""
  },
  {
    "hash": "38ed2da",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "feat: Enhance PWA configuration",
    "body": ""
  },
  {
    "hash": "a605f03",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "feat: Enhance service worker implementation",
    "body": ""
  },
  {
    "hash": "407d9ea",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "fix: Update PWA configuration for GitHub Pages",
    "body": ""
  },
  {
    "hash": "17760d1",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "fix: Update PWA paths in index.html",
    "body": ""
  },
  {
    "hash": "89186a4",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "fix: Update PWA paths for GitHub Pages deployment",
    "body": ""
  },
  {
    "hash": "3b4d518",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "fix: Update PWA paths for GitHub Pages deployment",
    "body": ""
  },
  {
    "hash": "4eb83e0",
    "date": "2025-01-10",
    "author": "Muhammad Faiz",
    "subject": "feat: Add PWA features section to README",
    "body": "This commit adds a new section to the README.md file\ndetailing the Progressive Web App (PWA) features of the\nAbacus Simulator. This includes installation instructions,\noffline capabilities, and benefits of using the app as a PWA.\nThis enhances the user experience by providing clear\nguidance on how to install and use the app effectively."
  },
  {
    "hash": "b92bd56",
    "date": "2025-01-09",
    "author": "Muhammad Faiz",
    "subject": "feat: Add translated README, addition, and subtraction guides, and update README links",
    "body": ""
  },
  {
    "hash": "d26ebcd",
    "date": "2025-01-09",
    "author": "Muhammad Faiz",
    "subject": "feat: Add translated README, addition, and subtraction guides, and update README links",
    "body": ""
  },
  {
    "hash": "a717ff1",
    "date": "2025-01-09",
    "author": "Muhammad Faiz",
    "subject": "Fix: Correct 5's complement message, update translations, and enhance game logic",
    "body": "- Corrected the 5's complement message in  to dynamically\n  include the correct complement value.\n- Updated the  translation in  to use a\n  generic translation.\n- Added  to ignore  and other unnecessary files.\n- ** Enhancements:**\n    - Added a  method and modified the  method to use it,\n      ensuring that required services are available before proceeding with game\n      initialization.\n    - Modified  to remove and recreate the game modal on\n      language change.\n    - Added  method to remove existing tutorial modals.\n    - Modified the  click handler to use\n      for animation.\n    - Added  method to handle bead highlighting\n      during tutorial and game.\n    - Added  method to animate the bead movements during\n      complement steps.\n    - Enhanced the service check with parallel loading in the\n      event listener.\n- ** Enhancements:**\n    - Added a check at the beginning of  to prevent negative\n      results.\n    - Updated the  object with new translations.\n    - Modified the borrow logic to handle cases where multiple borrows are needed.\n    - Improved the complement logic for subtraction.\n    - Modified  to handle sequential bead movements.\n    - Modified  to calculate and animate all intermediate\n      steps.\n    - Added a check to prevent null steps.\n- No significant changes in  and ."
  },
  {
    "hash": "91e8cc6",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Enhance language switching and fix Current Value label translation",
    "body": ""
  },
  {
    "hash": "21df0b3",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Enhance bead movement animations and fix initialization sequence",
    "body": ""
  },
  {
    "hash": "88e43f1",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Optimize script loading sequence for reliable initialization",
    "body": ""
  },
  {
    "hash": "a6b6e49",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Enhance script loading sequence with defer attributes for reliable initialization",
    "body": ""
  },
  {
    "hash": "2697e3f",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Enhance service initialization with parallel loading and robust dependency checks",
    "body": ""
  },
  {
    "hash": "1a8ec9e",
    "date": "2025-01-05",
    "author": "Muhammad Faiz",
    "subject": "Add systematic dependency checking for more reliable service initialization",
    "body": ""
  }
];
