/**
 * Changelog modal for Aloha (ported from Hand-Math changelog view).
 * Renders window.ALOHA_CHANGELOG (generated by scripts/generateChangelog.js)
 * and wires the "Check for updates" button to the update checker.
 */
(function () {
  'use strict';

  function renderChangelog() {
    var list = document.getElementById('alohaChangelogList');
    if (!list) return;
    list.innerHTML = '';
    var entries = window.ALOHA_CHANGELOG || [];
    if (!entries.length) {
      var empty = document.createElement('p');
      empty.textContent = 'No changelog entries found.';
      list.appendChild(empty);
      return;
    }
    entries.forEach(function (c) {
      var item = document.createElement('div');
      item.className = 'aloha-changelog-item';
      var head = document.createElement('div');
      head.className = 'aloha-changelog-head';
      head.textContent = (c.hash || '') + ' · ' + (c.date || '') + ' · ' + (c.subject || '');
      item.appendChild(head);
      if (c.body) {
        var body = document.createElement('pre');
        body.className = 'aloha-changelog-body';
        body.textContent = c.body;
        item.appendChild(body);
      }
      list.appendChild(item);
    });
  }

  function toggleChangelog(open) {
    var modal = document.getElementById('alohaChangelogModal');
    if (!modal) return;
    if (open) renderChangelog();
    modal.hidden = !open;
  }

  function init() {
    var openBtns = document.querySelectorAll('[data-aloha-changelog-open]');
    openBtns.forEach(function (b) {
      b.addEventListener('click', function () { toggleChangelog(true); });
    });
    var closeBtns = document.querySelectorAll('[data-aloha-changelog-close]');
    closeBtns.forEach(function (b) {
      b.addEventListener('click', function () { toggleChangelog(false); });
    });
    var checkBtn = document.getElementById('alohaBtnCheckUpdates');
    if (checkBtn) {
      checkBtn.addEventListener('click', function () {
        if (window.alohaUpdateChecker) {
          window.alohaUpdateChecker.checkForUpdate(true);
        } else if (window.AlohaUpdateChecker) {
          window.alohaUpdateChecker = new window.AlohaUpdateChecker();
          window.alohaUpdateChecker.checkForUpdate(true);
        }
      });
    }
    // Auto-start the release update checker (APK + PWA); silent on failure.
    try {
      if (window.AlohaUpdateChecker && !window.alohaUpdateChecker) {
        window.alohaUpdateChecker = new window.AlohaUpdateChecker();
        window.alohaUpdateChecker.start();
      }
    } catch (e) {
      console.warn('[changelogUI] update checker start failed:', e);
    }
  }

  window.alohaChangelog = { toggle: toggleChangelog, render: renderChangelog };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
