const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const targetFile = path.join(__dirname, '..', 'js', 'changelog.js');

try {
  const output = execSync(
    'git log -n 30 --pretty=format:"COMMIT_START%n%h%n%ad%n%an%n%s%n%b%nCOMMIT_END" --date=short',
    { encoding: 'utf-8' }
  );

  const commits = [];
  const rawCommits = output.split(/COMMIT_START\r?\n/);

  for (const raw of rawCommits) {
    if (!raw.trim()) continue;
    const cleanRaw = raw.split(/COMMIT_END/)[0].trim();
    const lines = cleanRaw.split(/\r?\n/);
    if (lines.length >= 4) {
      commits.push({
        hash: lines[0].trim(),
        date: lines[1].trim(),
        author: lines[2].trim(),
        subject: lines[3].trim(),
        body: lines.slice(4).join('\n').trim(),
      });
    }
  }

  const content =
    `// This file is auto-generated by scripts/generateChangelog.js. Do not edit directly.\n` +
    `window.ALOHA_CHANGELOG = ${JSON.stringify(commits, null, 2)};\n`;

  fs.writeFileSync(targetFile, content, 'utf-8');
  console.log(`Successfully generated changelog with ${commits.length} commits at ${targetFile}`);
} catch (error) {
  console.error('Error generating changelog:', error.message);
  const fallback =
    `// Fallback file - generation failed or not in git repo\nwindow.ALOHA_CHANGELOG = [];\n`;
  fs.writeFileSync(targetFile, fallback, 'utf-8');
}
