/**
 * Stage the static web app into www/ for Capacitor.
 *
 * Mirrors Hand-Math scripts/prepare-www.js: copies only files the app
 * actually loads at runtime into git-ignored www/ (regenerated by
 * `npm run cap:prepare`). The web app itself is untouched.
 *
 * Output: www/ (git-ignored; regenerated by `npm run cap:prepare`).
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WWW = path.join(ROOT, 'www');

// Top-level files copied verbatim into www/.
const ROOT_FILES = [
  'index.html',
  'language-select.html',
  'manifest.json',
  'sw.js',
  'config.js',
  'version.json',
  'latest.json',
  'favicon.ico',
  'styles.css',
  'arithmetic.css',
  'game.css',
  'positions.css',
  'tutorial.css',
  'addition.js',
  'arithmetic.js',
  'game.js',
  'language-selector.js',
  'movements.js',
  'script.js',
  'subtraction.js',
  'translations.js',
  'tutorial.js',
  'translation.csv',
];

// Directories copied recursively into www/.
const ROOT_DIRS = ['js', 'icons', 'assets', 'screenshots'];

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(s, d);
    } else if (entry.isFile()) {
      copyFile(s, d);
    }
  }
}

function main() {
  if (fs.existsSync(WWW)) {
    fs.rmSync(WWW, { recursive: true, force: true });
  }
  fs.mkdirSync(WWW, { recursive: true });

  for (const name of ROOT_FILES) {
    const src = path.join(ROOT, name);
    if (!fs.existsSync(src)) {
      throw new Error(`prepare-www: required file missing: ${name}`);
    }
    copyFile(src, path.join(WWW, name));
  }

  for (const name of ROOT_DIRS) {
    const src = path.join(ROOT, name);
    if (!fs.existsSync(src)) {
      throw new Error(`prepare-www: required directory missing: ${name}`);
    }
    copyDir(src, path.join(WWW, name));
  }

  // Sanity check: auto-generated changelog must be present (used by the
  // changelog modal; generated by scripts/generateChangelog.js).
  if (!fs.existsSync(path.join(WWW, 'js', 'changelog.js'))) {
    throw new Error('prepare-www: js/changelog.js missing — run `npm run generate-changelog` first');
  }

  let files = 0;
  let bytes = 0;
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(p);
      } else {
        files += 1;
        bytes += fs.statSync(p).size;
      }
    }
  })(WWW);

  console.log(`prepare-www: staged ${files} files (${(bytes / 1024 / 1024).toFixed(1)} MB) into www/`);
}

main();
